
/* AUTO-GENERATED by gen_isr_tables.py, do not edit! */

#include <zephyr/toolchain.h>
#include <zephyr/linker/sections.h>
#include <zephyr/sw_isr_table.h>
#include <zephyr/arch/cpu.h>

typedef void (* ISR)(const void *);
uintptr_t __irq_vector_table _irq_vector_table[218] = {
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
	((uintptr_t)&_isr_wrapper),
};
struct _isr_table_entry __sw_isr_table _sw_isr_table[218] = {
	{(const void *)0x3008ac60, (ISR)0x300617df}, /* 0 */
	{(const void *)0x3008ac60, (ISR)0x300617fd}, /* 1 */
	{(const void *)0x3008ac60, (ISR)0x3006181b}, /* 2 */
	{(const void *)0x3008ac60, (ISR)0x30061839}, /* 3 */
	{(const void *)0x3008ac60, (ISR)0x30061857}, /* 4 */
	{(const void *)0x3008ac60, (ISR)0x30061875}, /* 5 */
	{(const void *)0x3008ac60, (ISR)0x30061893}, /* 6 */
	{(const void *)0x3008ac60, (ISR)0x300618b1}, /* 7 */
	{(const void *)0x3008ac60, (ISR)0x300618cf}, /* 8 */
	{(const void *)0x3008ac60, (ISR)0x300618ed}, /* 9 */
	{(const void *)0x3008ac60, (ISR)0x3006190b}, /* 10 */
	{(const void *)0x3008ac60, (ISR)0x30061929}, /* 11 */
	{(const void *)0x3008ac60, (ISR)0x30061947}, /* 12 */
	{(const void *)0x3008ac60, (ISR)0x30061965}, /* 13 */
	{(const void *)0x3008ac60, (ISR)0x30061983}, /* 14 */
	{(const void *)0x3008ac60, (ISR)0x300619a1}, /* 15 */
	{(const void *)0x3008ac60, (ISR)0x30015da5}, /* 16 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 17 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 18 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 19 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 20 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 21 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 22 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 23 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 24 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 25 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 26 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 27 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 28 */
	{(const void *)0x3008ac90, (ISR)0x300655ad}, /* 29 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 30 */
	{(const void *)0x3008aca8, (ISR)0x300655ad}, /* 31 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 32 */
	{(const void *)0x3008ae28, (ISR)0x30063f83}, /* 33 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 34 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 35 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 36 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 37 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 38 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 39 */
	{(const void *)0x3008ae70, (ISR)0x30065f15}, /* 40 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 41 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 42 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 43 */
	{(const void *)0x3008af60, (ISR)0x30060455}, /* 44 */
	{(const void *)0x3008af60, (ISR)0x30060455}, /* 45 */
	{(const void *)0x3008af78, (ISR)0x30060455}, /* 46 */
	{(const void *)0x3008af78, (ISR)0x30060455}, /* 47 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 48 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 49 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 50 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 51 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 52 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 53 */
	{(const void *)0x3008afa8, (ISR)0x300614ab}, /* 54 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 55 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 56 */
	{(const void *)0x3008ac78, (ISR)0x30061a73}, /* 57 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 58 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 59 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 60 */
	{(const void *)0x3008ad08, (ISR)0x30062911}, /* 61 */
	{(const void *)0x3008ad08, (ISR)0x30062911}, /* 62 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 63 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 64 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 65 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 66 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 67 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 68 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 69 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 70 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 71 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 72 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 73 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 74 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 75 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 76 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 77 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 78 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 79 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 80 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 81 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 82 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 83 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 84 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 85 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 86 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 87 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 88 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 89 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 90 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 91 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 92 */
	{(const void *)0x3008adb0, (ISR)0x30062911}, /* 93 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 94 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 95 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 96 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 97 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 98 */
	{(const void *)0x3008adf8, (ISR)0x30062911}, /* 99 */
	{(const void *)0x3008acc0, (ISR)0x30062911}, /* 100 */
	{(const void *)0x3008acc0, (ISR)0x30062911}, /* 101 */
	{(const void *)0x3008adc8, (ISR)0x30062911}, /* 102 */
	{(const void *)0x3008adc8, (ISR)0x30062911}, /* 103 */
	{(const void *)0x3008ade0, (ISR)0x30062911}, /* 104 */
	{(const void *)0x3008ade0, (ISR)0x30062911}, /* 105 */
	{(const void *)0x3008acd8, (ISR)0x30062911}, /* 106 */
	{(const void *)0x3008acd8, (ISR)0x30062911}, /* 107 */
	{(const void *)0x3008acf0, (ISR)0x30062911}, /* 108 */
	{(const void *)0x3008acf0, (ISR)0x30062911}, /* 109 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 110 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 111 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 112 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 113 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 114 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 115 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 116 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 117 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 118 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 119 */
	{(const void *)0x3008aed0, (ISR)0x30060fc1}, /* 120 */
	{(const void *)0x3008aee8, (ISR)0x30060fc1}, /* 121 */
	{(const void *)0x3008af00, (ISR)0x30060fc1}, /* 122 */
	{(const void *)0x3008af18, (ISR)0x30060fc1}, /* 123 */
	{(const void *)0x3008af30, (ISR)0x30060fc1}, /* 124 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 125 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 126 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 127 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 128 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 129 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 130 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 131 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 132 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 133 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 134 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 135 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 136 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 137 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 138 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 139 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 140 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 141 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 142 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 143 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 144 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 145 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 146 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 147 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 148 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 149 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 150 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 151 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 152 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 153 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 154 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 155 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 156 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 157 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 158 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 159 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 160 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 161 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 162 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 163 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 164 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 165 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 166 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 167 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 168 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 169 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 170 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 171 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 172 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 173 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 174 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 175 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 176 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 177 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 178 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 179 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 180 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 181 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 182 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 183 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 184 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 185 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 186 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 187 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 188 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 189 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 190 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 191 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 192 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 193 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 194 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 195 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 196 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 197 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 198 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 199 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 200 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 201 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 202 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 203 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 204 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 205 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 206 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 207 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 208 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 209 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 210 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 211 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 212 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 213 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 214 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 215 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 216 */
	{(const void *)0x0, (ISR)z_irq_spurious}, /* 217 */
};
